apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysqlsvc-deployment
spec:
  replicas: 1 # tells deployment to run x pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: mysqlsvc-app
    spec:
      containers:
      - name: mysqlsvc
        image: mysql
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql 
          name: mysql-home
        args:
          - "--ignore-db-dir"
          - "lost+found"
        env:
          - name: MYSQL_ROOT_PASSWORD
            # change this
            value: REPLACEMYSQLPASSWORD
      volumes:
      - name: mysql-home
        persistentVolumeClaim:
          claimName: mysql-pv

