apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drupal-deployment
spec:
  replicas: 1 # tells deployment to run x pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: drupal-app
    spec:
      containers:
      - name: drupal
        image: drupal
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:       
          # testing nfs mount
        - mountPath: "/var/www/html/sites"
          name: nfs-sites
        - mountPath: "/var/www/html/modules"
          name: nfs-modules
        - mountPath: "/var/www/html/profiles"
          name: nfs-profiles
        - mountPath: "/var/www/html/themes"
          name: nfs-themes
      volumes:
        - name: nfs-sites
          persistentVolumeClaim:
            claimName: nfs-sites
        - name: nfs-modules
          persistentVolumeClaim:
            claimName: nfs-modules
        - name: nfs-profiles
          persistentVolumeClaim:
            claimName: nfs-profiles
        - name: nfs-themes
          persistentVolumeClaim:
            claimName: nfs-themes
      securityContext:  #mount the disks as www-data instead of the default Root - waiting for Azure files to support fsGroup
        fsGroup: 33
