apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-server-deployment
spec:
  replicas: 1 # tells deployment to run x pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: nfs-server-app
    spec:
      containers:
      - name: nfs-server
        image: gcr.io/google-samples/nfs-server:1.1
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: nfs-server-pv
      volumes:
        - name: nfs-server-pv
          persistentVolumeClaim:
            claimName: nfs-server-pvc
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: az-std-disk
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "nfs-server-pvc"
  annotations:
    volume.beta.kubernetes.io/storage-class: "az-std-disk"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app: nfs-server-app