apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-sites-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.244.1.4
    path: "/exports"
