kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-sites
  labels:
spec:
  volumeName: nfs-sites
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-sites
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 10.0.195.104
    path: "/sites"
