kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-sites
  labels:
spec:
  volumeName: nfs-sites
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-themes
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: REPLACENFSSERVERIP
    path: "/themes"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-modules
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: REPLACENFSSERVERIP
    path: "/modules"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-profiles
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: REPLACENFSSERVERIP
    path: "/profiles"

